# Generated by Django 4.0.4 on 2023-04-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('resolution', models.CharField(max_length=160, unique=True)),
                ('link', models.CharField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=160)),
                ('movie_thumb', models.ImageField(upload_to='product_thumb')),
                ('movie_screenshot1', models.ImageField(upload_to='product_img')),
                ('movie_screenshot2', models.ImageField(upload_to='product_img')),
                ('movie_screenshot3', models.ImageField(upload_to='product_img')),
                ('movie_screenshot4', models.ImageField(upload_to='product_img')),
                ('imb_rating', models.FloatField()),
                ('movie_pulished_date', models.DateField()),
                ('movie_duration', models.CharField(max_length=80)),
                ('movie_language', models.CharField(max_length=160)),
                ('movie_trailer_link', models.CharField(max_length=160)),
                ('movie_stream_link', models.CharField(max_length=160)),
                ('permalink', models.CharField(max_length=70, unique=True)),
                ('download_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.downloadlink')),
                ('movie_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
