# Generated by Django 4.0.4 on 2023-04-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_movie_download_links_movie_download_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_screenshot1',
            field=models.ImageField(upload_to='movie_screenshot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_screenshot2',
            field=models.ImageField(upload_to='movie_screenshot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_screenshot3',
            field=models.ImageField(upload_to='movie_screenshot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_screenshot4',
            field=models.ImageField(upload_to='movie_screenshot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_thumb',
            field=models.ImageField(upload_to='movie_thumb'),
        ),
    ]
