# Generated by Django 4.0.4 on 2023-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_movie_movie_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slide_movies', models.ManyToManyField(blank=True, to='home.movie')),
            ],
        ),
    ]
