# Generated by Django 4.0.4 on 2023-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_movies', models.ManyToManyField(blank=True, to='home.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
