# Generated by Django 4.0.4 on 2023-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_movie_movie_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlink',
            name='link',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='downloadlink',
            name='resolution',
            field=models.CharField(max_length=160),
        ),
    ]
