# Generated by Django 4.0.4 on 2023-04-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_downloadlink_link_alter_downloadlink_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_ad', models.TextField(default='')),
                ('side_ad', models.TextField(default='')),
                ('simple_content_ad', models.TextField(default='')),
                ('footer_ad', models.TextField(default='')),
                ('fixed_ad', models.TextField(default='')),
                ('show_fixed_ad', models.BooleanField(default=False, verbose_name='show fixed ad')),
            ],
        ),
    ]
