# Generated by Django 4.0.4 on 2023-04-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='side_ad',
        ),
    ]
