# Generated by Django 4.0.4 on 2023-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_ads_side_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('white_text_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('email', models.CharField(default='', max_length=160)),
                ('facebook', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=160, null=True)),
                ('made_by', models.CharField(default='', max_length=160)),
                ('copyright', models.CharField(default='', max_length=160)),
                ('custome_css', models.TextField(blank=True, default='', null=True)),
                ('head_script', models.TextField(blank=True, default='', null=True)),
                ('bodyend_script', models.TextField(blank=True, default='', null=True)),
                ('show_ads', models.BooleanField(default=False, verbose_name='show all ad')),
            ],
        ),
    ]
