# Generated by Django 4.0.4 on 2023-04-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_sitedata_white_text_logo_alter_sitedata_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keyword',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='meta_description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='meta_keyword',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=160),
        ),
    ]
