# Generated by Django 4.0.4 on 2023-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_movie_keyword_sitedata_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='site_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
