# Generated by Django 4.0.4 on 2023-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sitedata_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='site_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
