# Generated by Django 4.0.4 on 2023-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_movie_meta_description_movie_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', max_length=160),
        ),
    ]
