# Generated by Django 4.0.4 on 2023-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedata',
            name='movie_banner_min_height',
            field=models.CharField(default='520px', max_length=100),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='movie_box_height',
            field=models.CharField(default='550px', max_length=100),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='slider_box_height',
            field=models.CharField(default='450px', max_length=100),
        ),
    ]
