# Generated by Django 4.0.4 on 2023-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_sitedata_latest_post_section_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_stream_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_imdb_id',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_stream_cutome_link',
            field=models.CharField(default='', max_length=260),
        ),
    ]
