# Generated by Django 4.0.4 on 2023-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_movie_movie_stream_link_movie_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_imdb_id',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_stream_cutome_link',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
    ]
