# Generated by Django 4.0.4 on 2023-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_movie_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslider',
            name='slider_heading',
            field=models.CharField(default='', max_length=260),
        ),
    ]
