# Generated by Django 4.0.4 on 2023-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_movieslider_slider_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_tmbd_id',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
    ]
