# Generated by Django 4.0.4 on 2023-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_movie_movie_tmbd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.CharField(blank=True, default='', max_length=260, null=True),
        ),
    ]
