# Generated by Django 4.0.4 on 2023-04-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_movie_movie_title_movie_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='stream_movie_title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_year',
            new_name='stream_movie_year',
        ),
    ]
