# Generated by Django 4.0.4 on 2023-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_movie_title_movie_stream_movie_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stream_episode_number',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='stream_season_number',
            field=models.FloatField(null=True),
        ),
    ]
