# Generated by Django 4.0.4 on 2023-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_movie_stream_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stream_movie_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
