# Generated by Django 4.0.4 on 2023-04-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_movie_stream_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stream_movie_title',
            new_name='stream_movie_or_show_title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='stream_movie_year',
            new_name='stream_movie_or_show_year',
        ),
    ]
