# Generated by Django 4.0.4 on 2023-05-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(default='', max_length=160)),
                ('movies_by_category', models.OneToOneField(blank=True, default='None', on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('selected_movies', models.ManyToManyField(blank=True, to='home.movie')),
            ],
        ),
    ]
