# Generated by Django 4.0.4 on 2023-05-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_homesections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesections',
            name='movies_by_category',
            field=models.OneToOneField(blank=True, default='None', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category'),
        ),
    ]
