# Generated by Django 4.0.4 on 2023-05-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_homesections_movies_by_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stream_episode_number',
            new_name='stream_total_episode',
        ),
    ]
