# Generated by Django 4.0.4 on 2023-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_stream_episode_number_movie_stream_total_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('meta_desc', models.CharField(max_length=160)),
                ('meta_key', models.CharField(max_length=260)),
                ('page_name', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
